public class Informacoes {
    public static void mostrarInformacoes() {
        int opcao;
        do {
            Tela.limparTela();
            System.out.println("╔══════════════════════════════════════╗");
            System.out.println("║              INFORMAÇÕES             ║");
            System.out.println("╠══════════════════════════════════════╣");
            System.out.println("║                                      ║");
            System.out.println("║   1 - Combate                        ║");
            System.out.println("║   2 - Turnos                         ║");
            System.out.println("║   3 - Efeitos                        ║");
            System.out.println("║   4 - Itens                          ║");
            System.out.println("║   5 - Voltar                         ║");
            System.out.println("║                                      ║");
            System.out.println("╚══════════════════════════════════════╝");
            System.out.print("\nEscolha uma opção: ");
            opcao=Tela.lerInteiro();
            switch(opcao){case 1->mostrarCombate();case 2->mostrarTurnos();case 3->mostrarEfeitos();case 4->mostrarItens();case 5->{}default->{System.out.println("\nOpção inválida!");Tela.esperarEnter();}}
        } while(opcao!=5);
    }
    public static void mostrarCombate(){Tela.limparTela();System.out.print("=============== COMBATE ===============\n\nO combate em VESTIGIUM acontece por turnos.\nLuke enfrenta diferentes inimigos e deve utilizar\nsuas habilidades, armas e itens para sobreviver.\n\nOBJETIVO\nO objetivo do combate e reduzir a vida do inimigo\na 0 HP antes que a vida de Luke chegue a 0 HP.\n\nDURANTE O COMBATE\nEm seu turno, Luke pode escolher uma acao.\nAs acoes podem causar dano, utilizar itens ou\ninteragir com os efeitos presentes no combate.\n\nATAQUES\nCada ataque possui um valor de dano proprio.\nAlguns ataques tambem podem aplicar efeitos negativos\nao inimigo.\n\nEFEITOS\nAlguns ataques possuem chance de causar efeitos,\ncomo sangramento, queimadura ou envenenamento.\nEsses efeitos podem alterar o resultado do combate\nmesmo depois que o ataque termina.\n\nVIDA\nLuke inicia seus combates com 100 HP.\nCaso seus HP cheguem a 0, Luke sera derrotado.\nO inimigo tambem sera derrotado ao chegar a 0 HP.\n\nVITORIA\nO combate termina quando a vida do inimigo chega\na 0 HP.\n\nDERROTA\nSe a vida de Luke chegar a 0 HP, o combate sera\nencerrado e o jogador sera derrotado.\n");Tela.esperarEnter();}
    public static void mostrarTurnos(){Tela.limparTela();System.out.print("================ TURNOS ================\n\nO combate e dividido em turnos.\nCada turno representa uma nova rodada de acoes\nentre Luke e seu inimigo.\n\nINICIO DO TURNO\nNo inicio de cada turno, o jogo verifica os efeitos\nque estao ativos em Luke e no inimigo.\n\nTURNO DE LUKE\nO jogador escolhe uma acao para Luke realizar.\nA acao escolhida pode ser um ataque ou a utilizacao\nde um item, dependendo das opcoes disponiveis.\n\nTURNO DO INIMIGO\nDepois da acao de Luke, o inimigo realiza sua acao.\nCada inimigo possui comportamentos e ataques proprios.\n\nEFEITOS\nOs efeitos ativos continuam sendo considerados\ndurante os turnos, seguindo suas regras especificas.\n\nPROXIMO TURNO\nDepois que Luke e o inimigo realizarem suas acoes,\no turno termina e uma nova rodada comeca.\n\nO combate continua dessa forma ate que Luke ou\no inimigo seja derrotado.\n");Tela.esperarEnter();}
    public static void mostrarEfeitos(){Tela.limparTela();System.out.print("================ EFEITOS ================\n\nOs efeitos sao condicoes que alteram o estado de\nLuke ou dos inimigos durante o combate.\n\nSANGRAMENTO\nO sangramento representa uma perda continua de vida.\n\n- Causa 5% de dano por turno.\n- O dano continua enquanto o efeito estiver ativo.\n- O efeito deve ser tratado para ser removido.\n- Se nao for tratado dentro de 7 turnos,\n  Luke sofrera morte por hemorragia no turno seguinte.\n\nQUEIMADURA\nA queimadura representa danos causados por fogo ou\noutras fontes de calor extremo.\n\n- Causa 10% de dano quando aplicada.\n- Reduz a forca de Luke em 30% enquanto estiver ativa.\n- Pode permanecer ativa por no maximo 5 turnos.\n\nENVENENAMENTO\nO veneno causa um dano que aumenta progressivamente.\n\n- Comeca causando 1% de dano.\n- O dano aumenta em 1% a cada turno.\n- O efeito continua aumentando enquanto estiver ativo.\n- Pode ser removido utilizando o item adequado.\n\nACUMULO DE EFEITOS\nOs efeitos nao podem ser acumulados.\nSe Luke ja estiver sob determinado efeito, o mesmo\nefeito nao podera ser aplicado novamente enquanto\na condicao ainda estiver ativa.\n");Tela.esperarEnter();}
    public static void mostrarItens(){Tela.limparTela();System.out.print("================ ITENS ================\n\nOs itens sao recursos que podem auxiliar Luke\ndurante sua jornada e principalmente durante os combates.\n\nUTILIZACAO\nOs itens podem ser utilizados para recuperar recursos,\ntratar efeitos negativos ou obter vantagens durante\ndeterminadas situacoes.\n\nITENS DE CURA\nItens de cura recuperam parte da vida de Luke.\nEles devem ser utilizados com cuidado para evitar\nque Luke seja derrotado durante o combate.\n\nANTIDOTO\nO antidoto e utilizado para remover o envenenamento.\nSua utilizacao pode ser importante contra inimigos\nque possuem ataques capazes de envenenar Luke.\n\nTRATAMENTO DE EFEITOS\nAlguns itens possuem a funcao de remover efeitos\nnegativos aplicados durante o combate.\n\nESTRATEGIA\nOs itens sao recursos limitados. Por isso, o jogador\ndeve avaliar o momento correto para utiliza-los.\nUsar um item muito cedo pode desperdiçar um recurso,\nenquanto esperar demais pode resultar na derrota.\n");Tela.esperarEnter();}
}
