import personagens.*;
import mecanicas.evolucao.Evolucao;

public class Jogo {
    public static void iniciarJogo() {
        Tela.limparTela();
        Luke luke=new Luke(); Mutante mutante1=new Mutante(); Mutante mutante2=new Mutante();
        mutante2.vidaMaxima=120; mutante2.vida=120; mutante2.forca=10; mutante2.resistencia=5; mutante2.evasao=10;
        Seguranca seguranca=new Seguranca(); Cientista cientista=new Cientista(); Lucius lucius=new Lucius();
        Tela.mostrarTexto("Antes de iniciar sua jornada,","distribua seus pontos entre os atributos","de Luke Carmesin.");
        Tela.limparTela(); Evolucao.distribuirAtributos(luke,Tela.SC); Tela.limparTela();
        t("Luke deixa a cidade e segue em direção às florestas.","Quanto mais avança, mais evidente se torna","que algo naquele lugar está errado.");
        t("Árvores quebradas, solo escurecido","e um cheiro estranho tomam conta do ambiente.","");
        t("Ao longe, Luke escuta um som agressivo.","Galhos se quebram entre a vegetação.","Algo se aproxima rapidamente.");
        t("Uma criatura deformada surge entre as árvores.","Seu corpo apresenta feridas e alterações incomuns.","Ela avança contra Luke sem hesitar.");
        Combate.combateMutante(luke,mutante1); if(luke.vida<=0)return;
        t("Com a criatura caída, Luke se aproxima.","Agora, com mais calma, consegue observar","o que antes parecia apenas um monstro.");
        t("A estrutura do corpo ainda lembra um animal.","Apesar das deformações, Luke reconhece","traços semelhantes aos de um macaco.");
        t("Aquilo não nasceu daquela forma.","Alguma coisa havia alterado completamente","o corpo e o comportamento daquele animal.");
        t("Luke observa o solo ao redor.","Resíduos estranhos e marcas de contaminação","se espalham pela floresta.");
        t("A criatura não era a origem do problema.","Era apenas um dos seus vestígios.","");
        Evolucao.distribuirAtributos(luke,Tela.SC); Tela.limparTela();
        t("Luke continua avançando pela floresta devastada.","Entre árvores mortas e solo contaminado,","ele encontra um rio cortando a região.");
        t("A água está completamente corrompida.","Uma corrente escura, coberta por resíduos,","carrega um forte cheiro químico.");
        t("Luke observa a direção da correnteza.","A contaminação não surgiu ali.","Algo estava despejando aquilo no rio.");
        t("Ele começa a seguir contra a correnteza,","procurando a origem daquela destruição.","");
        t("Depois de algum tempo, um som rompe o silêncio.","Não era um rugido.","Era um gemido de dor.");
        t("Luke encontra uma criatura entre as árvores.","Seu corpo está tão deformado que é difícil","reconhecer que tipo de animal aquilo um dia foi.");
        t("Membros irregulares e feridas cobrem seu corpo.","Entre as deformações, alguns poucos traços","ainda lembram vagamente os de um cachorro.");
        t("A criatura se debate violentamente contra o chão.","Morde a própria carne e golpeia o próprio corpo,","desesperada para fazer a dor parar.");
        t("Sangue escorre das feridas que ela mesma abriu.","Mesmo assim, continua se mutilando.","A dor parece maior que seu instinto de sobrevivência.");
        t("Luke permanece imóvel por alguns segundos.","Depois de 2.500 anos observando a humanidade,","poucas coisas ainda conseguiam perturbá-lo.");
        t("","Aquilo conseguiu.","");
        t("A criatura finalmente percebe a presença de Luke.","Confusa, enlouquecida pela dor e pelo medo,","ela avança.");
        t("Luke desembainha sua espada.","Desta vez, ele sabe que vencer aquela criatura","também significa colocar fim ao seu sofrimento.");
        Combate.combateMutante(luke,mutante2); if(luke.vida<=0)return;
        t("O corpo da criatura finalmente para de se debater.","Os gemidos desaparecem.","A floresta volta ao silêncio.");
        t("Luke observa as feridas espalhadas pelo corpo.","Muitas não foram causadas pela batalha.","A própria criatura havia rasgado sua carne.");
        t("Aquilo não era um monstro.","Era um animal condenado a uma existência","de dor por algo que jamais poderia compreender.");
        t("Luke fecha os olhos do animal.","Depois cava uma pequena sepultura","e enterra o que restou dele.");
        t("Não havia honra naquela morte.","Não havia vitória.","Apenas uma vítima a menos sofrendo.");
        t("Luke retorna para a margem do rio.","Agora, a contaminação diante dele","carregava um significado diferente.");
        t("Alguém havia provocado aquilo.","E se alguém conhecia as consequências","e ainda assim continuava...");
        t("Luke fecha os punhos com força.","A indignação que sentia até então","havia se transformado em fúria.");
        t("Durante séculos, ele viu homens destruírem","vidas em nome de poder, riqueza e progresso.","Mas aquilo havia ultrapassado qualquer limite.");
        t("Se havia alguém por trás daquela atrocidade,","Luke não pretendia apenas encontrá-lo.","Pretendia fazê-lo responder pelo que havia feito.");
        Evolucao.distribuirAtributos(luke,Tela.SC); Tela.limparTela();
        t("Luke continua seguindo o rio contra a correnteza.","A cada passo, os sinais de destruição","se tornam mais intensos.");
        t("Árvores foram derrubadas em grandes extensões.","O solo foi rasgado por máquinas pesadas","e enormes áreas foram reduzidas a lama e resíduos.");
        t("Depois de algum tempo, Luke encontra a origem","de parte da contaminação.","Um grande tubo despeja resíduos diretamente no rio.");
        t("O líquido que sai dali é escuro e espesso.","O mesmo material que corre pela floresta","e transforma animais em criaturas deformadas.");
        t("Luke observa o local ao redor.","Máquinas, estruturas industriais e áreas de extração","ocupam grande parte daquela região.");
        t("Não era um acidente isolado.","Aquilo fazia parte de uma operação organizada","e continuava funcionando normalmente.");
        t("Luke segue em direção às instalações.","Sua expressão permanece fria,","mas a fúria ainda cresce dentro dele.");
        t("Antes que consiga entrar,","um homem armado bloqueia sua passagem.","");
        t("\"Pare aí.\"","\"Esta área é restrita.\"","\"Volte por onde veio.\"");
        t("Luke observa o homem por alguns segundos.","O uniforme e a arma deixam claro","que ele trabalha para aquela instalação.");
        t("\"Você sabe o que estão fazendo aqui?\"","pergunta Luke.","");
        t("\"Não é problema meu.\"","\"Sou pago para proteger este lugar.\"","\"E é exatamente isso que vou fazer.\"");
        t("Luke olha novamente para o rio contaminado.","Depois, para o homem diante dele.","");
        t("\"Então você escolheu proteger isso.\"","","");
        t("O segurança segura o rifle com mais força.","Luke não demonstra intenção de recuar.","A conversa termina ali.");
        Combate.combateSeguranca(luke,seguranca); if(luke.vida<=0)return;
        t("O segurança cai no chão.","Luke se aproxima lentamente,","mantendo os olhos sobre ele.");
        t("\"Eu só estava fazendo meu trabalho...\"","diz o homem, tentando recuperar o fôlego.","");
        t("Luke permanece em silêncio por alguns segundos.","Depois olha para as máquinas funcionando","atrás dos muros da instalação.");
        t("\"Todos escolhem o que estão dispostos","a fazer em troca de dinheiro.\"","");
        t("\"Cumprir ordens não apaga","as consequências delas.\"","");
        t("Luke deixa o segurança para trás.","Ele não era a origem daquele problema.","Era apenas mais uma peça mantendo tudo funcionando.");
        t("Luke atravessa a entrada da instalação.","Se queria encontrar o responsável,","precisava continuar avançando.");
        Evolucao.distribuirAtributos(luke,Tela.SC); Tela.limparTela();
        t("Luke avança pelos corredores da instalação.","Tubulações, tanques e equipamentos ocupam","boa parte daquele complexo.");
        t("O cheiro químico é ainda mais forte ali dentro.","Resíduos escorrem por canaletas no chão","e desaparecem por sistemas de drenagem.");
        t("Em uma das salas, Luke encontra","um homem cercado por frascos, anotações","e equipamentos de laboratório.");
        t("O homem ergue os olhos lentamente.","Ele não parece surpreso.","");
        t("\"Então você conseguiu entrar.\"","diz o cientista.","\"Imaginei que o segurança não conseguiria pará-lo.\"");
        t("Luke observa os recipientes espalhados pela sala.","Alguns contêm líquidos escuros.","Outros, amostras de tecido deformado.");
        t("\"Você sabe o que isso está causando?\"","pergunta Luke.","");
        t("O cientista sorri discretamente.","\"É claro que sei.\"","\"Eu ajudei a desenvolver parte do processo.\"");
        t("Luke permanece em silêncio.","Por alguns segundos,","a sala parece ainda mais fria.");
        t("\"Animais estão sendo deformados.\"","diz Luke.","\"A floresta está morrendo.\"");
        t("\"Consequências inevitáveis.\"","responde o cientista.","\"Todo avanço exige algum tipo de sacrifício.\"");
        t("Luke encara o homem diante dele.","A fúria retorna imediatamente.","");
        t("\"Você chama isso de avanço?\"","\"Transformar vidas em sofrimento","apenas porque você consegue?\"");
        t("O cientista ajusta as luvas.","\"Conhecimento existe para ser usado.\"","\"Limites são obstáculos impostos por quem tem medo.\"");
        t("Luke dá um passo à frente.","","");
        t("\"Conhecimento sem responsabilidade","não é inteligência.\"","");
        t("\"É apenas poder nas mãos","de alguém incapaz de compreender","as consequências do que faz.\"");
        t("O sorriso do cientista desaparece.","Ele pega alguns frascos sobre a bancada.","");
        t("\"Você fala como se estivesse acima de nós.\"","\"Mas no fim, você também resolve tudo","com violência.\"");
        t("Luke desembainha sua espada.","\"A diferença é que eu sei","por que estou usando a minha.\"");
        Combate.combateCientista(luke,cientista); if(luke.vida<=0)return;
        t("O cientista cai entre os equipamentos quebrados.","Frascos e instrumentos estão espalhados","pelo chão do laboratório.");
        t("Luke se aproxima.","O homem tenta se afastar,","mas não consegue continuar lutando.");
        t("\"Vai me matar?\"","pergunta o cientista.","");
        t("\"Não.\"","responde Luke.","");
        t("\"Morrer seria simples demais.\"","\"Você sabia exatamente","o que estava fazendo.\"");
        t("Luke encontra um par de algemas","entre os equipamentos de segurança","e prende as mãos do cientista.");
        t("\"Você vai responder por isso.\"","\"Não para mim.\"","\"Para todos que foram afetados por suas escolhas.\"");
        t("Luke deixa o cientista imobilizado.","O laboratório já não parece","um lugar de conhecimento.");
        t("Parece apenas o resultado","do que acontece quando inteligência","e responsabilidade deixam de caminhar juntas.");
        Evolucao.distribuirAtributos(luke,Tela.SC); Tela.limparTela();
        t("Luke continua avançando pelas instalações.","Até chegar a uma grande sala no centro","do complexo industrial.");
        t("No outro lado da sala,","um homem o aguarda.","");
        t("\"Luke Carmesin.\"","diz o homem.","\"Finalmente.\"");
        t("Luke observa Lucius Varn.","O homem responsável pela operação","permanece completamente tranquilo.");
        t("\"Florestas destruídas.\"","\"Água contaminada.\"","\"Animais transformados em aberrações.\"");
        t("\"Você sabe exatamente","o que está acontecendo aqui.\"","");
        t("\"É claro que sei.\"","responde Lucius.","\"Eu apenas não finjo que o progresso é gratuito.\"");
        t("\"Toda civilização foi construída","sobre alguma forma de destruição.\"","\"Eu só aceitei essa realidade.\"");
        t("\"E mesmo conhecendo as consequências,","você continua.\"","diz Luke.");
        t("\"Homens como eu constroem o futuro.\"","\"Homens como você perdem tempo","se preocupando com as consequências.\"");
        t("\"Você não está construindo um futuro.\"","\"Está consumindo tudo ao seu redor","e chamando a destruição de progresso.\"");
        t("\"Todo progresso tem um preço.\"","diz Lucius.","\"E eu estou disposto a pagá-lo.\"");
        t("\"Você nunca pagou esse preço.\"","responde Luke.","\"Quem pagou foram aqueles que nunca tiveram escolha.\"");
        t("Lucius sorri.","\"O mundo sempre pertenceu","àqueles fortes o bastante para moldá-lo.\"");
        t("\"Eu já vi homens acreditarem nisso antes.\"","diz Luke.","\"Nenhum deles terminou como imaginava.\"");
        t("Lucius aciona um mecanismo.","Partes metálicas começam a envolver seu corpo.","");
        t("Um exoesqueleto pesado se fecha ao redor dele.","Motores e sistemas mecânicos entram em funcionamento.","");
        t("\"Não estou aqui para julgá-lo.\"","diz Luke.","\"Suas próprias escolhas já fizeram isso por você.\"");
        Combate.combateLucius(luke,lucius);
        if(luke.vida<=0){
            t("Luke cai no chão.","Seu corpo já não consegue continuar lutando.","");
            t("Lucius observa Luke por alguns segundos.","\"Você poderia ter simplesmente ido embora.\"","");
            t("\"No fim, você era apenas","mais um obstáculo no caminho.\"","");
            t("As máquinas continuam funcionando.","Os resíduos continuam sendo despejados.","Nada muda.");
            t("Com o passar do tempo,","novas criaturas surgem.","A contaminação continua se espalhando.");
            t("Florestas desaparecem.","Rios morrem.","Ecossistemas inteiros entram em colapso.");
            t("A humanidade continua avançando","até perceber tarde demais","que havia destruído aquilo que a mantinha viva.");
            t("","DERROTA",""); return;
        }
        t("O exoesqueleto de Lucius começa a falhar.","Faíscas escapam das placas metálicas.","Os motores perdem força.");
        t("Lucius cai de joelhos.","Pela primeira vez,","sua expressão demonstra incerteza.");
        t("\"Você realmente acha que isso muda alguma coisa?\"","pergunta Lucius.","");
        t("\"Se eu parar, outro continuará.\"","\"Sempre haverá alguém disposto","a fazer o que eu fiz.\"");
        t("\"Talvez.\"","responde Luke.","\"Mas escolhas não são inevitáveis.\"");
        t("\"O mundo não chegou até aqui sozinho.\"","\"Pessoas escolheram trazê-lo até aqui.\"","");
        t("Com Lucius derrotado,","a operação finalmente é interrompida.","");
        t("As máquinas param.","O tubo deixa de despejar resíduos no rio.","O silêncio retorna lentamente.");
        t("A floresta não se recuperará rapidamente.","Talvez algumas marcas permaneçam","por décadas.");
        t("Mas, pela primeira vez em muito tempo,","existe a possibilidade","de que algo volte a crescer.");
        t("","VITÓRIA","");
        t("Alguns vestígios contam o que aconteceu.","Outros servem para lembrar","o que não deve se repetir.");
    }
    private static void t(String a,String b,String c){Tela.mostrarTexto(a,b,c);}
}
